"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Account = { id:string; email:string; name:string; picture?:string; storage:{limit:number|null;usage:number;usageInTrash:number} };
type DriveFile = { id:string; name:string; mimeType:string; size?:string; modifiedTime?:string; webViewLink?:string; accountId:string; ownedByMe?:boolean; shared?:boolean; driveId?:string; parents?:string[]; owners?:{displayName?:string;emailAddress?:string;photoLink?:string}[]; capabilities?:{canDownload?:boolean;canTrash?:boolean;canDelete?:boolean;canCopy?:boolean;canEdit?:boolean;canRemoveMyDriveParent?:boolean} };
type Upload = { id:string; name:string; progress:number; status:"uploading"|"done"|"error"; error?:string };
const GB=1024**3;
const bytes=(n:number)=>n>=GB?`${(n/GB).toFixed(1)} GB`:n>=1024**2?`${(n/1024**2).toFixed(1)} MB`:`${Math.max(0,Math.round(n/1024))} KB`;
const fileKind=(mime:string)=>mime.includes("folder")?"Folder":mime.includes("spreadsheet")?"Sheet":mime.includes("presentation")?"Slides":mime.includes("document")?"Doc":mime.startsWith("image")?"Image":mime.startsWith("video")?"Video":mime.includes("pdf")?"PDF":"File";
const icon=(mime:string)=>({Folder:"▰",Sheet:"▦",Slides:"▤",Doc:"≡",Image:"◫",Video:"▶",PDF:"PDF",File:"□"})[fileKind(mime)];
async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,headers:{...(init?.body?{"content-type":"application/json"}:{}),...init?.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error((data as {error?:string}).error||`Request failed (${response.status})`);return data as T;}
function LogoMark({large=false}:{large?:boolean}){return <span className={`logo-mark${large?" logo-mark-large":""}`} aria-hidden="true"><i/><b/></span>}

export default function LiveDashboard(){
 const [accounts,setAccounts]=useState<Account[]>([]),[files,setFiles]=useState<DriveFile[]>([]),[selected,setSelected]=useState<string[]>([]),[uploads,setUploads]=useState<Upload[]>([]);
 const [accountId,setAccountId]=useState("all"),[view,setView]=useState<"files"|"trash">("files"),[search,setSearch]=useState(""),[destination,setDestination]=useState(""),[ownedOnly,setOwnedOnly]=useState(false);
 const [loading,setLoading]=useState(true),[filesLoading,setFilesLoading]=useState(false),[busy,setBusy]=useState(false),[transferOpen,setTransferOpen]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState("");
 const uploadInput=useRef<HTMLInputElement>(null);
 const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(""),3500)};
 const loadAccounts=useCallback(async()=>{setLoading(true);try{const result=await api<{accounts:Account[];errors?:{message:string}[]}>("/api/accounts");setAccounts(result.accounts);if(result.errors?.length)setError(result.errors.map(x=>x.message).join(" · "));}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{loadAccounts();const p=new URLSearchParams(location.search);if(p.get("error"))setError(p.get("error")!);if(p.get("connected")){notify("Google Drive connected");history.replaceState({},"","/")}},[loadAccounts]);
 const loadFiles=useCallback(async()=>{if(!accounts.length){setFiles([]);return}setFilesLoading(true);setSelected([]);try{const targets=accountId==="all"?accounts:accounts.filter(a=>a.id===accountId);const groups=await Promise.all(targets.map(async a=>{const p=new URLSearchParams({accountId:a.id,trashed:String(view==="trash")});if(search.trim())p.set("q",search.trim());const r=await api<{files:Omit<DriveFile,"accountId">[]}>(`/api/files?${p}`);return r.files.map(f=>({...f,accountId:a.id}))}));setFiles(groups.flat().sort((a,b)=>(b.modifiedTime||"").localeCompare(a.modifiedTime||"")))}catch(e){setError((e as Error).message)}finally{setFilesLoading(false)}},[accounts,accountId,view,search]);
 useEffect(()=>{const timer=setTimeout(loadFiles,250);return()=>clearTimeout(timer)},[loadFiles]);
 const totals=useMemo(()=>accounts.reduce((s,a)=>({used:s.used+a.storage.usage,total:s.total+(a.storage.limit||0)}),{used:0,total:0}),[accounts]),pct=totals.total?Math.round(totals.used/totals.total*100):0;
 const visibleFiles=ownedOnly?files.filter(f=>f.ownedByMe):files;
 const chosen=files.filter(f=>selected.includes(f.id)),source=chosen.length&&chosen.every(f=>f.accountId===chosen[0].accountId)?chosen[0].accountId:null;
 const canTrashSelection=chosen.length>0&&chosen.every(f=>f.capabilities?.canTrash);
 const canRemoveSelection=chosen.length>0&&chosen.every(f=>!f.ownedByMe&&f.capabilities?.canRemoveMyDriveParent&&f.parents?.length===1);
 async function upload(list:FileList|null){if(!list?.length)return;const target=accountId==="all"?accounts.reduce((best,a)=>(a.storage.limit||Infinity)-a.storage.usage>(best.storage.limit||Infinity)-best.storage.usage?a:best).id:accountId;for(const file of Array.from(list)){const id=crypto.randomUUID();setUploads(j=>[...j,{id,name:file.name,progress:0,status:"uploading"}]);try{const start=await api<{uploadId:string;chunkSize:number}>("/api/uploads/start",{method:"POST",body:JSON.stringify({accountId:target,name:file.name,mimeType:file.type||"application/octet-stream",size:file.size})});for(let offset=0;offset<file.size;offset+=start.chunkSize){const end=Math.min(offset+start.chunkSize,file.size),response=await fetch(`/api/uploads/${start.uploadId}`,{method:"PUT",headers:{"content-range":`bytes ${offset}-${end-1}/${file.size}`},body:file.slice(offset,end)});if(!response.ok&&response.status!==308){const body=await response.json().catch(()=>({}));throw new Error(body.error||`Upload failed (${response.status})`)}setUploads(j=>j.map(x=>x.id===id?{...x,progress:Math.round(end/file.size*100)}:x))}setUploads(j=>j.map(x=>x.id===id?{...x,status:"done",progress:100,error:undefined}:x));notify(`${file.name} uploaded`);await loadAccounts();await loadFiles()}catch(e){const message=(e as Error).message;setUploads(j=>j.map(x=>x.id===id?{...x,status:"error",error:message}:x));setError(`${file.name}: ${message}`)}}if(uploadInput.current)uploadInput.current.value=""}
 async function trash(value:boolean){const blocked=chosen.filter(f=>!f.capabilities?.canTrash);if(blocked.length)return setError(`${blocked.length} selected item(s) are shared or read-only and cannot be ${value?"moved to Trash":"restored"} by this account.`);setBusy(true);try{const grouped=Map.groupBy(chosen,f=>f.accountId);await Promise.all(Array.from(grouped,([id,items])=>api("/api/files",{method:"PATCH",body:JSON.stringify({accountId:id,fileIds:items.map(x=>x.id),trashed:value})})));notify(value?"Moved to Trash":"Items restored");await loadFiles();await loadAccounts()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function removeFromMyDrive(){if(!canRemoveSelection)return;setBusy(true);try{const grouped=Map.groupBy(chosen,f=>f.accountId);await Promise.all(Array.from(grouped,([id,items])=>api("/api/files",{method:"PATCH",body:JSON.stringify({accountId:id,fileIds:items.map(x=>x.id),action:"removeFromMyDrive"})})));notify("Removed from My Drive");await loadFiles()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function forever(){const blocked=chosen.filter(f=>!f.capabilities?.canDelete);if(blocked.length)return setError(`${blocked.length} selected item(s) cannot be permanently deleted because this account is not their owner.`);if(!confirm(`Permanently delete ${selected.length} item(s)? This cannot be undone.`))return;setBusy(true);try{const grouped=Map.groupBy(chosen,f=>f.accountId);await Promise.all(Array.from(grouped,([id,items])=>api("/api/files",{method:"DELETE",body:JSON.stringify({accountId:id,fileIds:items.map(x=>x.id)})})));notify("Permanently deleted");await loadFiles();await loadAccounts()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function transfer(){if(!source||!destination)return;setBusy(true);try{await api("/api/transfers",{method:"POST",body:JSON.stringify({sourceAccountId:source,destinationAccountId:destination,fileIds:selected})});setTransferOpen(false);setSelected([]);notify("Destination verified. Sources were kept.");await loadAccounts();await loadFiles()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function disconnect(id:string){if(!confirm("Disconnect this account? Its Google Drive files will not change."))return;try{await api(`/api/accounts?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(accountId===id)setAccountId("all");await loadAccounts();notify("Account disconnected")}catch(e){setError((e as Error).message)}}
 if(loading)return <main className="first-run"><LogoMark large/><h1>Opening MegaDrive</h1><p>Bringing your connected drives into focus…</p><div className="loader"/></main>;
 if(!accounts.length)return <main className="first-run"><div className="first-run-brand"><LogoMark large/><strong>MegaDrive</strong></div><span className="status-pill">PRIVATE BY DESIGN</span><h1>Every drive.<br/><em>One calm workspace.</em></h1><p>See capacity, find files, and move data safely across your Google accounts without losing track of what lives where.</p>{error&&<div className="error-banner">{error}</div>}<a className="google-connect" href="/api/auth/google/start"><b>G</b><span>Connect your first Google account<small>Takes less than a minute</small></span><i>→</i></a><div className="trust-row"><span>✓ Official Google authorization</span><span>✓ Encrypted on this device</span><span>✓ Sources stay protected</span></div><small className="setup-note">MegaDrive never asks for your Google password.</small></main>;
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><LogoMark/><span>MegaDrive<small>DRIVE COMMAND</small></span></div><nav><button className={view==="files"&&accountId==="all"?"nav-item active":"nav-item"} onClick={()=>{setView("files");setAccountId("all")}}><span>⌂</span> Overview</button><button className={view==="trash"?"nav-item active":"nav-item"} onClick={()=>setView("trash")}><span>♲</span> Trash</button></nav><div className="sidebar-label">CONNECTED ACCOUNTS</div><div className="account-nav">{accounts.map(a=><button key={a.id} className={accountId===a.id?"account-link selected-account":"account-link"} onClick={()=>{setAccountId(a.id);setView("files")}}><span className="avatar small">{a.picture?<img src={a.picture} alt=""/>:a.email[0].toUpperCase()}</span><span><strong>{a.name}</strong><small>{bytes(a.storage.usage)} used</small></span><i onClick={e=>{e.stopPropagation();disconnect(a.id)}}>×</i></button>)}</div><a className="connect-side" href="/api/auth/google/start">＋ Connect account</a><div className="privacy-note"><span>●</span><div><strong>Local & encrypted</strong><small>Transfers run through this device.</small></div></div></aside>
 <section className="content"><header className="topbar"><div className="search-wrap"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search connected drives…"/></div><a className="secondary compact" href="/api/auth/google/start">＋ Add account</a></header><div className="page"><div className="heading-row"><div><p className="eyebrow">LIVE GOOGLE DRIVE DATA</p><h1>{view==="trash"?"Trash":accountId==="all"?"Your storage":accounts.find(a=>a.id===accountId)?.name}</h1><p>{view==="trash"?"Restore items or permanently remove them.":`${accounts.length} connected account${accounts.length===1?"":"s"}, one private workspace.`}</p></div><div className="header-actions"><input ref={uploadInput} type="file" multiple hidden onChange={e=>upload(e.target.files)}/><button className="primary" onClick={()=>uploadInput.current?.click()}>↑ Upload files</button></div></div>{error&&<div className="error-banner"><span>{error}</span><button onClick={()=>setError("")}>×</button></div>}
 {view==="files"&&<><section className="storage-hero"><div className="capacity-ring" style={{"--value":`${pct*3.6}deg`} as React.CSSProperties}><div><strong>{(totals.used/GB).toFixed(1)}</strong><span>GB used</span></div></div><div className="capacity-copy"><span className="status-pill">LIVE CAPACITY</span><h2>{totals.total?`${bytes(totals.total-totals.used)} available`:"Storage limit unavailable"}</h2><p>reported directly by Google Drive</p><div className="capacity-track"><span style={{width:`${pct}%`}}/></div><small>{pct}% used <b>{bytes(totals.total)} total</b></small></div><div className="insight"><span className="spark">✓</span><div><strong>Your files stay in Google Drive</strong><p>Transfers keep the source until the destination copy passes verification.</p></div></div></section><section className="section-block"><div className="section-heading"><div><h2>Your accounts</h2><p>Current storage reported by Google</p></div></div><div className="account-grid">{accounts.map(a=>{const p=a.storage.limit?Math.round(a.storage.usage/a.storage.limit*100):0;return <article className="account-card" key={a.id} onClick={()=>setAccountId(a.id)}><div className="account-card-top"><span className="avatar">{a.picture?<img src={a.picture} alt=""/>:a.email[0]}</span><div><strong>{a.name}</strong><small>{a.email}</small></div></div><div className="account-stats"><strong>{bytes(a.storage.usage)} <span>of {a.storage.limit?bytes(a.storage.limit):"unlimited"}</span></strong><b className={p>85?"danger":""}>{p}%</b></div><div className="mini-track"><span style={{width:`${p}%`}}/></div><small>{bytes(a.storage.usageInTrash)} in Trash</small></article>})}</div></section></>}
 <section className="section-block files-section">
  <div className="section-heading"><div><h2>{view==="trash"?"Deleted items":"Files"}</h2><p>{filesLoading?"Loading from Google…":`${visibleFiles.length} item${visibleFiles.length===1?"":"s"} shown`}</p></div><div className="file-heading-actions">{view==="files"&&<label className="owned-filter"><input type="checkbox" checked={ownedOnly} onChange={e=>{setOwnedOnly(e.target.checked);setSelected([])}}/> Owned by me</label>}<button className="text-button" onClick={loadFiles}>↻ Refresh</button></div></div>
  {selected.length>0&&<div className="selection-bar"><strong>{selected.length} selected</strong>{view==="files"?<><button onClick={()=>{if(!source)return setError("Choose files from one source account per transfer.");setDestination(accounts.find(a=>a.id!==source)?.id||"");setTransferOpen(true)}}>⇄ Transfer</button><button disabled={busy||!canTrashSelection} title={!canTrashSelection?"One or more selected files cannot be trashed by this account":undefined} onClick={()=>trash(true)}>♲ Trash</button>{canRemoveSelection&&<button disabled={busy} onClick={removeFromMyDrive}>− Remove from My Drive</button>}</>:<><button disabled={busy||!canTrashSelection} onClick={()=>trash(false)}>↶ Restore</button><button disabled={busy} className="danger-action" onClick={forever}>Delete forever</button></>}<button onClick={()=>setSelected([])}>Clear</button></div>}
  <div className="file-table"><div className="file-row table-head"><span><input type="checkbox" checked={visibleFiles.length>0&&visibleFiles.every(f=>selected.includes(f.id))} onChange={()=>setSelected(visibleFiles.every(f=>selected.includes(f.id))?[]:visibleFiles.map(f=>f.id))}/> Name</span><span>Owner</span><span>Account</span><span>Size</span><span>Modified</span><span/></div>
   {filesLoading?<div className="empty-state"><div className="loader small-loader"/><p>Reading Google Drive…</p></div>:visibleFiles.length?visibleFiles.map(f=>{const a=accounts.find(x=>x.id===f.accountId)!;const owner=f.driveId?"Shared drive":f.owners?.[0]?.displayName||f.owners?.[0]?.emailAddress||(f.ownedByMe?a.name:"Unknown owner");const accessLabel=f.ownedByMe?"Owned":f.capabilities?.canEdit?"Shared · Editor":"Shared · Read-only";return <div className="file-row" key={`${f.accountId}-${f.id}`}><span className="file-name"><input type="checkbox" checked={selected.includes(f.id)} onChange={()=>setSelected(s=>s.includes(f.id)?s.filter(x=>x!==f.id):[...s,f.id])}/><i className={`file-icon ${fileKind(f.mimeType).toLowerCase()}`}>{icon(f.mimeType)}</i><span><strong>{f.name}</strong><small>{fileKind(f.mimeType)} <b className={`access-badge ${f.ownedByMe?"owned":f.capabilities?.canEdit?"shared":"readonly"}`}>{accessLabel}</b></small></span></span><span className="owner-cell" title={f.owners?.[0]?.emailAddress}>{owner}</span><span className="account-cell">{a.name}</span><span>{f.size?bytes(Number(f.size)):"—"}</span><span>{f.modifiedTime?new Date(f.modifiedTime).toLocaleDateString():"—"}</span>{f.webViewLink?<a href={f.webViewLink} target="_blank" rel="noreferrer">↗</a>:<span/>}</div>}):<div className="empty-state"><span>□</span><h3>{ownedOnly?"No files owned by this account":search?"No matching files":view==="trash"?"Trash is empty":"This Drive is empty"}</h3><p>{view==="files"&&!search&&!ownedOnly?"Upload a file to get started.":"Nothing to show here."}</p></div>}
  </div>
 </section></div></section>
 {uploads.length>0&&<div className="upload-panel"><strong>Uploads</strong><button onClick={()=>setUploads(x=>x.filter(j=>j.status==="uploading"))}>×</button>{uploads.map(j=><div className="upload-job" key={j.id}><span>{j.name}</span><small title={j.error}>{j.status==="error"?`Failed: ${j.error||"Unknown error"}`:`${j.progress}%`}</small><i><b style={{width:`${j.progress}%`}}/></i></div>)}</div>}
 {transferOpen&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setTransferOpen(false)}>×</button><span className="modal-symbol transfer-symbol">⇄</span><h2>Copy {selected.length} item{selected.length===1?"":"s"}</h2><p>The destination will be verified. Source files remain untouched.</p><label className="destination-label">Destination<select value={destination} onChange={e=>setDestination(e.target.value)}>{accounts.filter(a=>a.id!==source).map(a=><option value={a.id} key={a.id}>{a.email}</option>)}</select></label><div className="safe-transfer"><span>✓</span><div><strong>Source protection enabled</strong><small>Nothing is deleted during transfer.</small></div></div><button className="primary modal-action" disabled={busy||!destination} onClick={transfer}>{busy?"Copying and verifying…":"Start verified transfer"}</button></div></div>}{toast&&<div className="toast"><span>✓</span>{toast}</div>}</main>
}
